package com.cekhoax.bean;
// Generated Dec 27, 2016 5:15:33 PM by Hibernate Tools 4.3.1



/**
 * Cekuser generated by hbm2java
 */
public class Cekuser  implements java.io.Serializable {


     private String username;

    public Cekuser() {
    }

    public Cekuser(String username) {
       this.username = username;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


