package com.cekhoax.bean;
// Generated Dec 27, 2016 5:15:33 PM by Hibernate Tools 4.3.1



/**
 * Cekuser generated by hbm2java
 */
public class Cekuser  implements java.io.Serializable {


     private String email;

    public Cekuser() {
    }

    public Cekuser(String email) {
       this.email = email;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


