package com.cekhoax.bean;
// Generated Dec 27, 2016 10:01:20 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer idPost;
     private int idNama;
     private String judul;
     private String link;
     private String post;
     private String alasan;
     private Date tanggal;

    public Post() {
    }

    public Post(int idNama, String judul, String link, String post, String alasan, Date tanggal) {
       this.idNama = idNama;
       this.judul = judul;
       this.link = link;
       this.post = post;
       this.alasan = alasan;
       this.tanggal = tanggal;
    }
   
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }
    public int getIdNama() {
        return this.idNama;
    }
    
    public void setIdNama(int idNama) {
        this.idNama = idNama;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public String getAlasan() {
        return this.alasan;
    }
    
    public void setAlasan(String alasan) {
        this.alasan = alasan;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }




}


