package com.cekhoax.bean;
// Generated Dec 27, 2016 10:01:20 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idNama;
     private String username;
     private String email;
     private String notlp;
     private String password;

    public User() {
    }

    public User(String username, String email, String notlp, String password) {
       this.username = username;
       this.email = email;
       this.notlp = notlp;
       this.password = password;
    }
   
    public Integer getIdNama() {
        return this.idNama;
    }
    
    public void setIdNama(Integer idNama) {
        this.idNama = idNama;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNotlp() {
        return this.notlp;
    }
    
    public void setNotlp(String notlp) {
        this.notlp = notlp;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


